parameters:

services:

    matthias_common_app_infrastructure_common.message_queue:
      class: Matthias\Common\App\MessageQueue\StompMessageQueue
      arguments:
        - "%stomp_host%"
        - "%stomp_port%"
        - "%stomp_default_queue%"
        - "%stomp_user%"
        - "%stomp_password%"