parameters:

services:

    matthias_common_app_infrastructure_common.message_queue:
      class: Matthias\Common\App\MessageQueue\StompMessageQueue
      arguments:
        - "%stomp_host%"
        - "%stomp_port%"
        - "%stomp_default_queue%"
        - "%stomp_user%"
        - "%stomp_password%"
        - "@matthias_common_app_infrastructure_common.serializer"

    matthias_common_app_infrastructure_common.serializer:
      class: Matthias\Common\App\Infrastructure\CommonBundle\Serializer\SymfonySerializer
      arguments:
        - "@serializer"

    matthias_user_app_infrastructure_common.asynchronous_event_bus_middleware:
        class: Matthias\Common\App\Command\AsynchronousEventBusMiddleware
        arguments:
            - "@matthias_common_app_infrastructure_common.message_queue"
        tags:
            - { name: event_bus_middleware, priority: 0 }

    matthias_user_app_infrastructure_common.asynchronous_command_bus_middleware:
        class: Matthias\Common\App\Command\AsynchronousCommandBusMiddleware
        tags:
            - { name: command_bus_middleware, priority: 0 }