parameters:

services:

    matthias_user_app_infrastructure_command.register_user_command_handler:
        class: Matthias\User\App\Command\RegisterUserCommandHandler
        arguments:
            - "@event_recorder"
        tags:
            - { name: command_handler, handles: Matthias\User\App\Command\RegisterUserCommand }

    matthias_user_app_infrastructure_command.notification_mail_event_handler:
        class: Matthias\User\App\Event\SendNotificationMailAfterUserWasRegistered
        tags:
            - { name: event_subscriber, subscribes_to: Matthias\User\App\Event\UserWasRegisteredEvent }
