matthias_user_presentation_web:
    resource: "@MatthiasUserPresentationInfrastructureWebBundle/Resources/config/routing.yml"
    prefix:   /user

# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /user/signup
        permanent: true

