services:
    # override this alias to use a different entity manager
    asynchronous_bus.doctrine_orm_bridge.entity_manager:
        alias: doctrine.orm.entity_manager
        public: false

    asynchronous_bus.doctrine_orm_bridge.wraps_next_command_in_transaction:
        class: SimpleBus\DoctrineORMBridge\MessageBus\WrapsMessageHandlingInTransaction
        public: false
        arguments:
            - @asynchronous_bus.doctrine_orm_bridge.entity_manager
        tags:
            - { name: asynchronous_command_bus_middleware, priority: 100 }

    asynchronous_bus.doctrine_orm_bridge.aggregates_multiple_event_providers:
        class: SimpleBus\DoctrineORMBridge\EventListener\CollectsEventsFromEntities
        public: false
        tags:
            - { name: doctrine.event_subscriber }
            - { name: event_recorder }
