services:
    asynchronous_command_bus:
        alias: asynchronous_bus.asynchronous_command_bus

    asynchronous_bus.asynchronous_command_bus:
        class: SimpleBus\Message\Bus\Middleware\MessageBusSupportingMiddleware
        public: false

    asynchronous_bus.asynchronous_command_bus.delegates_to_message_handler_middleware:
        class: SimpleBus\Message\Handler\DelegatesToMessageHandlerMiddleware
        public: false
        arguments:
            - @asynchronous_bus.asynchronous_command_bus.command_handler_resolver
        tags:
            - { name: asynchronous_command_bus_middleware, priority: -1000 }

    asynchronous_bus.asynchronous_command_bus.class_based_command_name_resolver:
        class: SimpleBus\Message\Name\ClassBasedNameResolver
        public: false

    asynchronous_bus.asynchronous_command_bus.named_message_command_name_resolver:
        class: SimpleBus\Message\Name\NamedMessageNameResolver
        public: false

    asynchronous_bus.asynchronous_command_bus.command_handler_map:
        class: SimpleBus\Message\Handler\Map\LazyLoadingMessageHandlerMap
        public: false
        arguments:
            # collection of command handler service ids, will be provided by the RegisterHandlers compiler pass
            - []
            - @asynchronous_bus.asynchronous_command_bus.invokable_service_locator

    asynchronous_bus.asynchronous_command_bus.command_handler_resolver:
        class: SimpleBus\Message\Handler\Resolver\NameBasedMessageHandlerResolver
        public: false
        arguments:
            - @asynchronous_bus.asynchronous_command_bus.command_name_resolver
            - @asynchronous_bus.asynchronous_command_bus.command_handler_map

    asynchronous_bus.asynchronous_command_bus.invokable_service_locator:
        class: SimpleBus\SymfonyBridge\DependencyInjection\InvokableServiceLocator
        public: false
        arguments:
            - @service_container

    asynchronous_bus.asynchronous_command_bus.finishes_command_before_handling_next_middleware:
        class: SimpleBus\Message\Bus\Middleware\FinishesHandlingMessageBeforeHandlingNext
        public: false
        tags:
            - { name: asynchronous_command_bus_middleware, priority: 1000 }
