parameters:

services:
    matthias_user_app_infrastructure_user.asynchronous_event_bus_middleware:
        class: Matthias\Common\App\Command\AsynchronousEventBusMiddleware
        arguments:
            - "@matthias_common_app_infrastructure_common.message_queue"
        tags:
            - { name: event_bus_middleware, priority: 0 }

    matthias_user_app_infrastructure_user.asynchronous_command_bus_middleware:
        class: Matthias\Common\App\Command\AsynchronousCommandBusMiddleware
        tags:
            - { name: command_bus_middleware, priority: 0 }

imports:
- { resource: command_handlers.yml }
- { resource: event_subscribers.yml }
